package br.instrumentosmusicais.pdv.view;


import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class RelatorioAnaliticoView extends javax.swing.JFrame {

    public RelatorioAnaliticoView() {        
        initComponents();
    }
    public RelatorioAnaliticoView(String[] cliente, ArrayList<String[]> produto) {
        
        initComponents();
        tblTabelaProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblTabelaProdutosVenda.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblTabelaProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblTabelaProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(30);
        tblTabelaProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(30);
        
        
        txtNomeCliente.setText(cliente[3]);
        txtNomeCPF.setText(cliente[4]);
        txtNomeNCompra.setText(cliente[0]);
        txtNomeEndereco.setText(cliente[5]);
        txtNomeCidade.setText(cliente[6]);
        txtNomeTelefone.setText(cliente[7]);
        txtNomeEmail.setText(cliente[8]);  
        txtNomeData.setText(cliente[1]);
        
        

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tblTabelaProdutosVenda.getModel();
        

        for (String[] produtos : produto) {
            modelo.addRow(produtos);
            
        }    
        
        txtNomeTotal.setText("R$ "+String.valueOf(cliente[2]));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        txtDados = new javax.swing.JPanel();
        Esquerdo = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JLabel();
        txtNomeCPF = new javax.swing.JLabel();
        lblNomeCPF = new javax.swing.JLabel();
        lblNomeNCompra = new javax.swing.JLabel();
        txtNomeNCompra = new javax.swing.JLabel();
        Direito = new javax.swing.JPanel();
        lblNomeEndereco = new javax.swing.JLabel();
        txtNomeEndereco = new javax.swing.JLabel();
        lblNomeTelefone = new javax.swing.JLabel();
        txtNomeTelefone = new javax.swing.JLabel();
        lblNomeCidade = new javax.swing.JLabel();
        txtNomeCidade = new javax.swing.JLabel();
        lblNomeEmail = new javax.swing.JLabel();
        txtNomeEmail = new javax.swing.JLabel();
        tblProduto = new javax.swing.JScrollPane();
        tblTabelaProdutosVenda = new javax.swing.JTable();
        resumoGeral = new javax.swing.JPanel();
        lblNomeData = new javax.swing.JLabel();
        txtNomeData = new javax.swing.JLabel();
        lblNomeTotal = new javax.swing.JLabel();
        txtNomeTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Analítico");
        setResizable(false);

        pnlFundo.setBackground(new java.awt.Color(102, 102, 102));

        txtDados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblNomeCliente.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeCliente.setText("Cliente:");

        txtNomeCliente.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        txtNomeCPF.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        lblNomeCPF.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeCPF.setText("CPF:");

        lblNomeNCompra.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeNCompra.setText("Nº Compra:");

        txtNomeNCompra.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        javax.swing.GroupLayout EsquerdoLayout = new javax.swing.GroupLayout(Esquerdo);
        Esquerdo.setLayout(EsquerdoLayout);
        EsquerdoLayout.setHorizontalGroup(
            EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeNCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeNCompra, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCPF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        EsquerdoLayout.setVerticalGroup(
            EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeNCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeNCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNomeEndereco.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeEndereco.setText("Endereço:");

        txtNomeEndereco.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        lblNomeTelefone.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeTelefone.setText("Telefone:");

        txtNomeTelefone.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        lblNomeCidade.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeCidade.setText("Cidade:");

        txtNomeCidade.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        lblNomeEmail.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeEmail.setText("E-mail:");

        txtNomeEmail.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        javax.swing.GroupLayout DireitoLayout = new javax.swing.GroupLayout(Direito);
        Direito.setLayout(DireitoLayout);
        DireitoLayout.setHorizontalGroup(
            DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DireitoLayout.createSequentialGroup()
                        .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(txtNomeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DireitoLayout.createSequentialGroup()
                        .addComponent(lblNomeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DireitoLayout.createSequentialGroup()
                                .addComponent(txtNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))))
        );
        DireitoLayout.setVerticalGroup(
            DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DireitoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DireitoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout txtDadosLayout = new javax.swing.GroupLayout(txtDados);
        txtDados.setLayout(txtDadosLayout);
        txtDadosLayout.setHorizontalGroup(
            txtDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Esquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Direito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtDadosLayout.setVerticalGroup(
            txtDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtDadosLayout.createSequentialGroup()
                .addGroup(txtDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Esquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Direito, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblTabelaProdutosVenda.setBackground(new java.awt.Color(153, 153, 153));
        tblTabelaProdutosVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblTabelaProdutosVenda.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        tblTabelaProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Instrumento", "Preço", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabelaProdutosVenda.setRowHeight(20);
        tblTabelaProdutosVenda.setRowMargin(3);
        tblTabelaProdutosVenda.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblProduto.setViewportView(tblTabelaProdutosVenda);

        resumoGeral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblNomeData.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        lblNomeData.setText("DATA DA VENDA");

        txtNomeData.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        lblNomeTotal.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        lblNomeTotal.setText("TOTAL DA VENDA:");

        txtNomeTotal.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        javax.swing.GroupLayout resumoGeralLayout = new javax.swing.GroupLayout(resumoGeral);
        resumoGeral.setLayout(resumoGeralLayout);
        resumoGeralLayout.setHorizontalGroup(
            resumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resumoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeData, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeData, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        resumoGeralLayout.setVerticalGroup(
            resumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNomeData, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            .addComponent(txtNomeData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNomeTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNomeTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resumoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(tblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(txtDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDados, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resumoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnaliticoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnaliticoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnaliticoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnaliticoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioAnaliticoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Direito;
    private javax.swing.JPanel Esquerdo;
    private javax.swing.JLabel lblNomeCPF;
    private javax.swing.JLabel lblNomeCidade;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeData;
    private javax.swing.JLabel lblNomeEmail;
    private javax.swing.JLabel lblNomeEndereco;
    private javax.swing.JLabel lblNomeNCompra;
    private javax.swing.JLabel lblNomeTelefone;
    private javax.swing.JLabel lblNomeTotal;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel resumoGeral;
    private javax.swing.JScrollPane tblProduto;
    private javax.swing.JTable tblTabelaProdutosVenda;
    private javax.swing.JPanel txtDados;
    private javax.swing.JLabel txtNomeCPF;
    private javax.swing.JLabel txtNomeCidade;
    private javax.swing.JLabel txtNomeCliente;
    private javax.swing.JLabel txtNomeData;
    private javax.swing.JLabel txtNomeEmail;
    private javax.swing.JLabel txtNomeEndereco;
    private javax.swing.JLabel txtNomeNCompra;
    private javax.swing.JLabel txtNomeTelefone;
    private javax.swing.JLabel txtNomeTotal;
    // End of variables declaration//GEN-END:variables
}
