package br.instrumentosmusicais.pdv.view;

import br.instrumentosmusicais.pdv.controller.VendaController;
import br.instrumentosmusicais.pdv.utils.Validador;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

public class VendaView extends javax.swing.JFrame {
    
    public VendaView() {
        initComponents();
        tbProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(15);
        tbProdutosVenda.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(15);
        tbProdutosVenda.getColumnModel().getColumn(4).setPreferredWidth(30);
    }

    public VendaView(String codCliente, String nomeCliente, String CPF) {
        initComponents();
        tbProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(15);
        tbProdutosVenda.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(15);
        tbProdutosVenda.getColumnModel().getColumn(4).setPreferredWidth(30);

        lblCodClienteValor.setText(codCliente);
        txtNomeCliente.setText(nomeCliente);
        txtCPF.setText(CPF);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVenderEsq = new javax.swing.JPanel();
        pnlCliente = new javax.swing.JPanel();
        lblVender = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        lblCodCliente = new javax.swing.JLabel();
        btnPesquisarCliente = new javax.swing.JButton();
        lblMensagemErroNome = new javax.swing.JLabel();
        lblMensagemErroCPF = new javax.swing.JLabel();
        lblCodClienteValor = new javax.swing.JLabel();
        pnlProduto = new javax.swing.JPanel();
        lblQtdProduto = new javax.swing.JLabel();
        spnQtd = new javax.swing.JSpinner();
        lblCodProduto = new javax.swing.JLabel();
        btnAdicionarProduto = new javax.swing.JButton();
        txtNomeDoProduto = new javax.swing.JTextField();
        lblNomeDoProduto = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        lblMensagemErroCodProduto = new javax.swing.JLabel();
        pnlTabela = new javax.swing.JPanel();
        pnlValoresVender1 = new javax.swing.JPanel();
        lblDesconto = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotalValor = new javax.swing.JLabel();
        lblDescontoValor = new javax.swing.JLabel();
        lblSubtotalRS = new javax.swing.JLabel();
        lblDescontoRS = new javax.swing.JLabel();
        lblTotalValor = new javax.swing.JLabel();
        lblTotalRS = new javax.swing.JLabel();
        pnlTabelaVender = new javax.swing.JScrollPane();
        tbProdutosVenda = new javax.swing.JTable();
        btnFinalizarVenda = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblicone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");

        pnlVenderEsq.setBackground(new java.awt.Color(51, 51, 51));

        pnlCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblVender.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        lblVender.setText("Vender");

        lblNomeCliente.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeCliente.setText("Nome do Cliente*");

        txtNomeCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtCPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setToolTipText("");

        lblCodCliente.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblCodCliente.setText("CPF*");

        btnPesquisarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnPesquisarCliente.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnPesquisarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnPesquisarCliente.setContentAreaFilled(false);
        btnPesquisarCliente.setOpaque(true);
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        lblMensagemErroNome.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N

        lblMensagemErroCPF.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N

        lblCodClienteValor.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVender)
                            .addComponent(lblNomeCliente)
                            .addComponent(lblMensagemErroNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodCliente)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensagemErroCPF))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCodClienteValor)
                        .addContainerGap())))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVender)
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(lblCodCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMensagemErroNome)
                    .addComponent(lblMensagemErroCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodClienteValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblQtdProduto.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblQtdProduto.setText("Quantidade");

        spnQtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnQtd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblCodProduto.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblCodProduto.setText("Código do Produto*");

        btnAdicionarProduto.setBackground(new java.awt.Color(51, 51, 51));
        btnAdicionarProduto.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnAdicionarProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarProduto.setText("Adicionar");
        btnAdicionarProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnAdicionarProduto.setContentAreaFilled(false);
        btnAdicionarProduto.setOpaque(true);
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });

        txtNomeDoProduto.setBackground(new java.awt.Color(102, 102, 102));
        txtNomeDoProduto.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        txtNomeDoProduto.setText("Exemplo de produto");
        txtNomeDoProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        txtNomeDoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeDoProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeDoProdutoFocusLost(evt);
            }
        });
        txtNomeDoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoProdutoActionPerformed(evt);
            }
        });

        lblNomeDoProduto.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNomeDoProduto.setForeground(new java.awt.Color(204, 204, 204));
        lblNomeDoProduto.setText("Nome do Produto");

        txtCodProduto.setForeground(new java.awt.Color(204, 204, 204));
        txtCodProduto.setText("   Ex: 1234");
        txtCodProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodProdutoFocusLost(evt);
            }
        });
        txtCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdutoActionPerformed(evt);
            }
        });
        txtCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdutoKeyTyped(evt);
            }
        });

        lblMensagemErroCodProduto.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlProdutoLayout = new javax.swing.GroupLayout(pnlProduto);
        pnlProduto.setLayout(pnlProdutoLayout);
        pnlProdutoLayout.setHorizontalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdutoLayout.createSequentialGroup()
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodProduto)
                            .addGroup(pnlProdutoLayout.createSequentialGroup()
                                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMensagemErroCodProduto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutoLayout.createSequentialGroup()
                                .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))
                            .addGroup(pnlProdutoLayout.createSequentialGroup()
                                .addComponent(lblQtdProduto)
                                .addGap(70, 70, 70))))
                    .addGroup(pnlProdutoLayout.createSequentialGroup()
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeDoProduto)
                            .addComponent(txtNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        pnlProdutoLayout.setVerticalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProduto)
                    .addComponent(lblQtdProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensagemErroCodProduto))
                .addGap(15, 15, 15)
                .addComponent(lblNomeDoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnlProdutoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spnQtd, txtCodProduto});

        pnlTabela.setBackground(new java.awt.Color(102, 102, 102));

        pnlValoresVender1.setBackground(new java.awt.Color(51, 51, 51));

        lblDesconto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblDesconto.setForeground(new java.awt.Color(255, 255, 255));
        lblDesconto.setText("Desconto");

        lblSubtotal.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotal.setText("Subtotal");

        lblTotal.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");

        lblSubtotalValor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblSubtotalValor.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotalValor.setText("0,00");

        lblDescontoValor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblDescontoValor.setForeground(new java.awt.Color(255, 255, 255));
        lblDescontoValor.setText("0,00");

        lblSubtotalRS.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblSubtotalRS.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotalRS.setText("R$");

        lblDescontoRS.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblDescontoRS.setForeground(new java.awt.Color(255, 255, 255));
        lblDescontoRS.setText("R$");

        lblTotalValor.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        lblTotalValor.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalValor.setText("0,00");

        lblTotalRS.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblTotalRS.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalRS.setText("R$");

        javax.swing.GroupLayout pnlValoresVender1Layout = new javax.swing.GroupLayout(pnlValoresVender1);
        pnlValoresVender1.setLayout(pnlValoresVender1Layout);
        pnlValoresVender1Layout.setHorizontalGroup(
            pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValoresVender1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlValoresVender1Layout.createSequentialGroup()
                        .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesconto)
                            .addComponent(lblSubtotal))
                        .addGap(34, 34, 34)
                        .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescontoValor)
                            .addComponent(lblSubtotalValor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtotalRS)
                            .addComponent(lblDescontoRS)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValoresVender1Layout.createSequentialGroup()
                                .addGap(0, 121, Short.MAX_VALUE)
                                .addComponent(lblTotalValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalRS))))
                    .addGroup(pnlValoresVender1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotal)))
                .addGap(19, 19, 19))
        );
        pnlValoresVender1Layout.setVerticalGroup(
            pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValoresVender1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalValor)
                    .addComponent(lblTotalRS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblSubtotalValor)
                    .addComponent(lblSubtotalRS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlValoresVender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesconto)
                    .addComponent(lblDescontoValor)
                    .addComponent(lblDescontoRS))
                .addGap(26, 26, 26))
        );

        tbProdutosVenda.setBackground(new java.awt.Color(153, 153, 153));
        tbProdutosVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        tbProdutosVenda.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        tbProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Instrumento", "Preço", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutosVenda.setCellSelectionEnabled(true);
        tbProdutosVenda.setGridColor(new java.awt.Color(51, 51, 51));
        tbProdutosVenda.setRowHeight(20);
        tbProdutosVenda.setRowMargin(3);
        tbProdutosVenda.setSelectionBackground(new java.awt.Color(51, 51, 51));
        pnlTabelaVender.setViewportView(tbProdutosVenda);

        btnFinalizarVenda.setBackground(new java.awt.Color(51, 51, 51));
        btnFinalizarVenda.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnFinalizarVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarVenda.setText("<html>\nFinalizar\n<br>&nbsp;&nbsp;&nbsp;&nbsp;Venda\n</html>");
        btnFinalizarVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnFinalizarVenda.setContentAreaFilled(false);
        btnFinalizarVenda.setOpaque(true);
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(51, 51, 51));
        btnLimpar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setOpaque(true);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(51, 51, 51));
        btnExcluir.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir ");
        btnExcluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setOpaque(true);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabelaLayout = new javax.swing.GroupLayout(pnlTabela);
        pnlTabela.setLayout(pnlTabelaLayout);
        pnlTabelaLayout.setHorizontalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTabelaVender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlValoresVender1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTabelaLayout.createSequentialGroup()
                        .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlTabelaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcluir, btnLimpar});

        pnlTabelaLayout.setVerticalGroup(
            pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTabelaVender, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlValoresVender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlTabelaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcluir, btnLimpar});

        lblicone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MoedaTeste2.png"))); // NOI18N

        javax.swing.GroupLayout pnlVenderEsqLayout = new javax.swing.GroupLayout(pnlVenderEsq);
        pnlVenderEsq.setLayout(pnlVenderEsqLayout);
        pnlVenderEsqLayout.setHorizontalGroup(
            pnlVenderEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVenderEsqLayout.createSequentialGroup()
                .addGroup(pnlVenderEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVenderEsqLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVenderEsqLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblicone))
                    .addGroup(pnlVenderEsqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlVenderEsqLayout.setVerticalGroup(
            pnlVenderEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVenderEsqLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblicone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVenderEsqLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVenderEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVenderEsq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodProdutoFocusGained
        if (txtCodProduto.getText().equals("   Ex: 1234")) {
            txtCodProduto.setText("");
            txtCodProduto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCodProdutoFocusGained

    private void txtCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodProdutoFocusLost
        if (txtCodProduto.getText().equals("")) {
            txtCodProduto.setText("   Ex: 1234");
            txtCodProduto.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtCodProdutoFocusLost

    private void txtCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdutoActionPerformed

    private void txtCodProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdutoKeyTyped
        char c = evt.getKeyChar();

        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Digite apenas números no código do produto !");
        }
    }//GEN-LAST:event_txtCodProdutoKeyTyped

    private void txtNomeDoProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeDoProdutoFocusGained
        if (txtNomeDoProduto.getText().equals("Exemplo de produto")) {
            txtNomeDoProduto.setText("");
            txtNomeDoProduto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNomeDoProdutoFocusGained

    private void txtNomeDoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeDoProdutoFocusLost
        if (txtNomeDoProduto.getText().equals("")) {
            txtNomeDoProduto.setText("Exemplo de produto");
        }
    }//GEN-LAST:event_txtNomeDoProdutoFocusLost

    private void txtNomeDoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoProdutoActionPerformed

    }//GEN-LAST:event_txtNomeDoProdutoActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed

        String nome = txtNomeCliente.getText().trim();
        String CPF = txtCPF.getText().replace(".", "").replace("-", "").trim();

        //String[] infoCliente = PDVController.vendaBuscarCliente(nome, CPF);
        ArrayList<String[]> infoClientes = VendaController.vendaBuscarCliente(nome, CPF);

        if (infoClientes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");
            Validador objValidar = new Validador();
            objValidar.CampoVazio(txtNomeCliente, lblMensagemErroNome);
            objValidar.CampoVazioFormatado(txtCPF, lblMensagemErroCPF);
            return;
        }
        if (infoClientes.size() > 1) {
            SelecionarClienteView selecao = new SelecionarClienteView();
            selecao.preencherTabela(infoClientes);
            selecao.setVisible(true);
            dispose();

        } else {
            String[] info = infoClientes.get(0);

            lblCodClienteValor.setText(info[0]);
            txtNomeCliente.setText(info[1]);
            txtCPF.setText(info[2]);
            Validador objValidar = new Validador();
            objValidar.CampoVazio(txtNomeCliente, lblMensagemErroNome);
            objValidar.CampoVazioFormatado(txtCPF, lblMensagemErroCPF);

        }


    }//GEN-LAST:event_btnPesquisarClienteActionPerformed
    float valorTotalVenda = 0;
    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed
        Validador objValidar = new Validador();

        objValidar.CampoVazio(txtNomeCliente, lblMensagemErroNome);
        objValidar.CampoVazioFormatado(txtCPF, lblMensagemErroCPF);
        if (txtCodProduto.getText().equals("   Ex: 1234")) {
            txtCodProduto.setText("");
        } else {
            txtCodProduto.setForeground(Color.BLACK);
            txtCodProduto.setBackground(Color.WHITE);
        }
        float valorTotalProduto = 0;
        int linha = 0;
        String codigo = null;
        String instrumento = null;

        codigo = txtCodProduto.getText();
        instrumento = txtNomeDoProduto.getText();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tbProdutosVenda.getModel();

        ArrayList<String[]> produtos = VendaController.vendaBuscarProduto(codigo, instrumento);

        String[] addProduto;

        if (produtos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Produto não encontrado");
            return;
        } else if (produtos.size() > 1) {
            String produtosRepetidos = "\n";
            for (int i = 0; i < produtos.size(); i++) {
                produtosRepetidos = Arrays.toString(produtos.get(i)).replace("[", "").replace("]", "") + "\n" + produtosRepetidos;
            }
            JOptionPane.showMessageDialog(this, "Foram encontrados " + produtos.size() + " produtos\n\n" + produtosRepetidos + "Verifique o código do produto que deseja adicionar á venda e insira-o no campo Código do Produto");
            txtCodProduto.setText("");
            txtNomeDoProduto.setText("");
            if (txtNomeDoProduto.getText().equals("")) {
                txtNomeDoProduto.setText("Exemplo de produto");
            }
            if (txtCodProduto.getText().equals("")) {
                txtCodProduto.setText("   Ex: 1234");
                txtCodProduto.setForeground(new java.awt.Color(204, 204, 204));
            }
            return;
        } else {
            addProduto = produtos.get(0);
            int quantidadeEstoque = Integer.parseInt(addProduto[3]);
            int quantidade = Integer.parseInt(spnQtd.getValue().toString());
            float valor = Float.parseFloat(addProduto[2]);
            valorTotalProduto = valor * quantidade;

            txtCodProduto.setText(addProduto[0]);
            txtNomeDoProduto.setText(addProduto[1]);

            if (quantidade > quantidadeEstoque) {
                JOptionPane.showMessageDialog(this, "Quantidade em estoque insuficiente\nQuantidade em estoque: " + (quantidadeEstoque));
                return;
            }
            
            for(int i =0; i<modelo.getRowCount(); i++){
                
            if(addProduto[0].equals(modelo.getValueAt(i, 0).toString())){
            JOptionPane.showMessageDialog(this,"Produto já adicionado\n, caso deseja aumentar a quantidade vendida, exclua o produto da lista\n e adicione-o novamente com a quantidade desejada.");
            return;
            }
            }

            modelo.addRow(addProduto);
            modelo.setValueAt(spnQtd.getValue(), modelo.getRowCount() - 1, 3);
            modelo.setValueAt(valorTotalProduto, modelo.getRowCount() - 1, 4);
            linha++;
        }
        spnQtd.setValue(1);
        txtCodProduto.setText("");
        txtNomeDoProduto.setText("");
        if (txtNomeDoProduto.getText().equals("")) {
            txtNomeDoProduto.setText("Exemplo de produto");
        }
        if (txtCodProduto.getText().equals("")) {
            txtCodProduto.setText("   Ex: 1234");
            txtCodProduto.setForeground(new java.awt.Color(204, 204, 204));
        }

        valorTotalVenda = valorTotalProduto + valorTotalVenda;

        lblTotalValor.setText(String.valueOf(valorTotalVenda));
    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tbProdutosVenda.getModel();

        int codCliente = Integer.parseInt(lblCodClienteValor.getText());

        ArrayList<String[]> itens = new ArrayList<String[]>();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            itens.add(new String[]{
                String.valueOf(modelo.getValueAt(i, 0)), //codigo
                String.valueOf(modelo.getValueAt(i, 1)), //instrumento
                String.valueOf(modelo.getValueAt(i, 2)), //valor
                String.valueOf(modelo.getValueAt(i, 3))}); //quantidade
        }
        boolean retorno = VendaController.vendaVender(valorTotalVenda, codCliente, itens);

        if (retorno) {
            JOptionPane.showMessageDialog(this, "SUCESSO");
            modelo.setRowCount(0);
            txtCPF.setText("");
            txtNomeCliente.setText("");
            valorTotalVenda = 0;
            lblTotalValor.setText(String.valueOf(valorTotalVenda));
            
        } else {
            JOptionPane.showMessageDialog(this, "DEU ERRO");
        }


    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tbProdutosVenda.getModel();
        modelo.setRowCount(0);
        valorTotalVenda = 0;
        lblTotalValor.setText(String.valueOf(valorTotalVenda));
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tbProdutosVenda.getModel();
        int linhaSelecionada = tbProdutosVenda.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Para excluir o produto da lista, selecione a linha");
            return;
        } else {
            valorTotalVenda = valorTotalVenda - Float.parseFloat(modelo.getValueAt(linhaSelecionada, 4).toString());
            modelo.removeRow(linhaSelecionada);
            lblTotalValor.setText(String.valueOf(valorTotalVenda));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblCodClienteValor;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblDescontoRS;
    private javax.swing.JLabel lblDescontoValor;
    private javax.swing.JLabel lblMensagemErroCPF;
    private javax.swing.JLabel lblMensagemErroCodProduto;
    private javax.swing.JLabel lblMensagemErroNome;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeDoProduto;
    private javax.swing.JLabel lblQtdProduto;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalRS;
    private javax.swing.JLabel lblSubtotalValor;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalRS;
    private javax.swing.JLabel lblTotalValor;
    private javax.swing.JLabel lblVender;
    private javax.swing.JLabel lblicone;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlProduto;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JScrollPane pnlTabelaVender;
    private javax.swing.JPanel pnlValoresVender1;
    private javax.swing.JPanel pnlVenderEsq;
    private javax.swing.JSpinner spnQtd;
    private javax.swing.JTable tbProdutosVenda;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeDoProduto;
    // End of variables declaration//GEN-END:variables
}
